# Generated by Django 4.2.16 on 2026-04-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manažér'), ('developer', 'Vývojár'), ('designer', 'Dizajnér'), ('tester', 'Tester'), ('analyst', 'Analytik')], default='developer', max_length=20, verbose_name='Rola v projekte')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Dátum priradenia')),
            ],
            options={
                'verbose_name': 'Členstvo',
                'verbose_name_plural': 'Členstvá',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Názov')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dátum vytvorenia')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Termín odovzdania')),
                ('status', models.CharField(choices=[('planning', 'Plánovanie'), ('active', 'Aktívny'), ('on_hold', 'Pozastavený'), ('completed', 'Dokončený'), ('cancelled', 'Zrušený')], default='planning', max_length=20, verbose_name='Stav')),
                ('members', models.ManyToManyField(related_name='projects', through='projects.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Členovia')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Názov')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dátum vytvorenia')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Členovia')),
            ],
            options={
                'verbose_name': 'Tím',
                'verbose_name_plural': 'Tímy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Názov')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('priority', models.CharField(choices=[('low', 'Nízka'), ('medium', 'Stredná'), ('high', 'Vysoká'), ('critical', 'Kritická')], default='medium', max_length=10, verbose_name='Priorita')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Termín')),
                ('status', models.CharField(choices=[('todo', 'Na urobenie'), ('in_progress', 'V riešení'), ('review', 'Na kontrole'), ('done', 'Hotovo')], default='todo', max_length=15, verbose_name='Stav')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Riešiteľ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Úloha',
                'verbose_name_plural': 'Úlohy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.team', verbose_name='Tím'),
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'project')},
        ),
    ]
